development:
  sessions:
    default:
      database: kc_ckeditor_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: kc_ckeditor_test
      hosts:
        - localhost:27017